# Generated by Django 6.0.3 on 2026-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.FloatField(default=0, verbose_name='Estoque Atual'),
        ),
    ]
