# Generated by Django 6.0.3 on 2026-04-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='atualizado_em',
            new_name='atualizado',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='criado_em',
            new_name='criado',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='estoque_atual',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_compra',
            new_name='preco_de_compra',
        ),
    ]
