# Generated by Django 6.0.3 on 2026-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_atualizado_em_produto_atualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('LT', 'Litro'), ('CX', 'Caixa'), ('PCT', 'Pacote')], default='UN', max_length=20, verbose_name='Unidade'),
        ),
    ]
