# Generated by Django 6.0.3 on 2026-04-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_endereco_alter_fornecedor_nome'),
        ('movimentacoes', '0001_initial'),
        ('produtos', '0004_produto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='fornecedores.fornecedor'),
        ),
        migrations.AddField(
            model_name='saida',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas', to='produtos.produto'),
        ),
    ]
